In [31]:
# 1. 想知道會收門票的遊憩景點中哪一個是票價最高的?

import pandas as pd

# 賦予colab拜訪google drive的權限
from google.colab import drive
drive.mount('/content/drive')

# 存取我的雲端硬碟中practice這個資料夾中檔名為Tainan(2).csv.csv的檔案，並轉為Dataframe的形式
df = pd.read_csv('/content/drive/My Drive/practice/Tainan(2).csv.csv')

# # 列印出Dataframe形式的資料
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註
0,臺灣鹽博物館,-,-,-,-,-,-,門票數(自111年閉館整修)
1,七股鹽山,"19,359","7,532","14,926","11,965","$489,850","13,215",門票數
2,北門遊客中心,NaN,"30,549","15,337","15,212",NaN,"14,892",停車數概估
3,井仔腳瓦盤鹽田,NaN,"33,111","15,531","17,580",NaN,"12,983",停車數概估
4,柳營尖山埤渡假村,"7,771","4,194","5,897","6,068","$211,990","4,336",門票數
5,烏山頭水庫風景區,"22,047","1,829","6,674","17,202","$916,045","16,278",門票數
6,曾文水庫,"16,403","1,739","10,126","8,016","$925,942","12,684",門票數
7,關子嶺溫泉區,NaN,"74,173","43,290","30,883",NaN,"165,388",自動車流監視
8,虎頭埤風景區,"15,910","21,707","20,777","16,840","$893,862","26,779",門票數
9,南元休閒農場,"2,429","1,721","2,629","1,521","$594,945",524,門票數
10,走馬瀨農場,"13,425","7,491","12,442","8,474","$2,653,380","2,869",門票數
11,烏樹林休閒園區,NaN,"7,231","5,001","2,230",NaN,"1,084",門票數
12,頑皮世界,"21,124","2,321","12,511","10,934","$7,681,858","9,764",門票數
13,南鯤鯓代天府,NaN,"756,000","453,600","302,400",NaN,"720,000",廟方估計
14,麻豆代天府,NaN,"303,750","182,250","121,500",NaN,"59,558",廟方估計
15,馬沙溝濱海遊憩區,796,NaN,676,120,"$93,340",698,人工計數器
16,國立臺灣歷史博物館,"7,976","36,492","29,403","15,065","$808,450","21,496",門票數
17,奇美博物館,"29,315","10,933","16,635","23,613","$5,363,420","19,123",門票數
18,臺南市美術館,"15,036","15,394","15,396","15,034","$2,070,450","20,064",門票數及人工計數
19,臺南山上花園水道博物館,"11,880","6,279","11,289","6,870","$776,480","10,142",門票數及人工計數
20,臺南孔子廟,"7,799","3,900","5,195","6,504","$285,300","2,779",人工計數器
21,祀典武廟,NaN,"19,359","8,759","10,600",NaN,"7,438",人工計數器
22,赤崁樓,"17,670","9,986","12,513","15,143","$1,201,223","10,626",門票數
23,大天后宮,NaN,"22,125","10,010","12,115",NaN,"8,501",人工計數器
24,安平小鎮,"44,949","271,773","137,318","179,404","$2,662,310","20,592",門票數及電信人數推估(自112年1月更新統計方式)
25,南紡購物中心,NaN,"513,878","234,870","279,008",NaN,NaN,電信數據人數推估(自112年1月起統計)
26,新化老街,NaN,"134,217","49,380","84,837",NaN,NaN,電信數據人數推估(自112年1月起統計)
27,鹽水老街,NaN,"67,722","24,239","43,483",NaN,NaN,電信數據人數推估(自112年1月起統計)
28,黃金海岸,NaN,"20,905","8,343","12,562",NaN,NaN,電信數據人數推估(自112年1月起統計)
29,藍晒圖文創園區,NaN,"342,941","163,261","179,680",NaN,NaN,電信數據人數推估(自112年1月起統計)

In [49]:
# 將第一行臺灣鹽博物館的資料刪除
df_new = df.iloc[1:, :]

# 將門票收入、遊客人次假日、遊客人次非假日這三列具有千位分隔符號的逗號刪除掉
df_new['門票收入'] = df_new['門票收入'].str.replace(',', '')
df_new['遊客人次假日'] = df_new['遊客人次假日'].str.replace(',', '')
df_new['遊客人次非假日'] = df_new['遊客人次非假日'].str.replace(',', '')

# 將門票收入這一列值中含有的金錢符號刪除掉
df_new['門票收入'] = df_new['門票收入'].str.replace('$', '')

# 將門票收入這一列值中沒有資料(顯示NaN)的值替換為0
df_new.fillna(0, inplace=True)

# 列印出處理好的資料
df_new

<ipython-input-49-0f466302b6b0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['門票收入'] = df_new['門票收入'].str.replace(',', '')
<ipython-input-49-0f466302b6b0>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['遊客人次假日'] = df_new['遊客人次假日'].str.replace(',', '')
<ipython-input-49-0f466302b6b0>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['遊客人次非假日'] = df_new['遊客人次非假日'].str.replace(',', '')
<ipython-input-49-0f466302b6b0>:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_new['門票收入'] = df_new['門票收入'].str.replace('$', '')
<ipython-input-49-0f466302b6b0>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['門票收入'] = df_new['門票收入'].str.replace('$', '')
<ipython-input-49-0f466302b6b0>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new.fillna(0, inplace=True)

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註
1,七股鹽山,"19,359","7,532",14926,11965,489850,"13,215",門票數
2,北門遊客中心,0,"30,549",15337,15212,0,"14,892",停車數概估
3,井仔腳瓦盤鹽田,0,"33,111",15531,17580,0,"12,983",停車數概估
4,柳營尖山埤渡假村,"7,771","4,194",5897,6068,211990,"4,336",門票數
5,烏山頭水庫風景區,"22,047","1,829",6674,17202,916045,"16,278",門票數
6,曾文水庫,"16,403","1,739",10126,8016,925942,"12,684",門票數
7,關子嶺溫泉區,0,"74,173",43290,30883,0,"165,388",自動車流監視
8,虎頭埤風景區,"15,910","21,707",20777,16840,893862,"26,779",門票數
9,南元休閒農場,"2,429","1,721",2629,1521,594945,524,門票數
10,走馬瀨農場,"13,425","7,491",12442,8474,2653380,"2,869",門票數
11,烏樹林休閒園區,0,"7,231",5001,2230,0,"1,084",門票數
12,頑皮世界,"21,124","2,321",12511,10934,7681858,"9,764",門票數
13,南鯤鯓代天府,0,"756,000",453600,302400,0,"720,000",廟方估計
14,麻豆代天府,0,"303,750",182250,121500,0,"59,558",廟方估計
15,馬沙溝濱海遊憩區,796,0,676,120,93340,698,人工計數器
16,國立臺灣歷史博物館,"7,976","36,492",29403,15065,808450,"21,496",門票數
17,奇美博物館,"29,315","10,933",16635,23613,5363420,"19,123",門票數
18,臺南市美術館,"15,036","15,394",15396,15034,2070450,"20,064",門票數及人工計數
19,臺南山上花園水道博物館,"11,880","6,279",11289,6870,776480,"10,142",門票數及人工計數
20,臺南孔子廟,"7,799","3,900",5195,6504,285300,"2,779",人工計數器
21,祀典武廟,0,"19,359",8759,10600,0,"7,438",人工計數器
22,赤崁樓,"17,670","9,986",12513,15143,1201223,"10,626",門票數
23,大天后宮,0,"22,125",10010,12115,0,"8,501",人工計數器
24,安平小鎮,"44,949","271,773",137318,179404,2662310,"20,592",門票數及電信人數推估(自112年1月更新統計方式)
25,南紡購物中心,0,"513,878",234870,279008,0,0,電信數據人數推估(自112年1月起統計)
26,新化老街,0,"134,217",49380,84837,0,0,電信數據人數推估(自112年1月起統計)
27,鹽水老街,0,"67,722",24239,43483,0,0,電信數據人數推估(自112年1月起統計)
28,黃金海岸,0,"20,905",8343,12562,0,0,電信數據人數推估(自112年1月起統計)
29,藍晒圖文創園區,0,"342,941",163261,179680,0,0,電信數據人數推估(自112年1月起統計)

In [38]:
# 將門票收入為0的資料刪除掉
non_zero = df_new[df_new['門票收入'] != 0]

# 將門票收、遊客人次假日、由客人次非假日這三列的資料全部的數據轉換為數值
non_zero['門票收入'] = pd.to_numeric(non_zero['門票收入'])
non_zero['遊客人次假日'] = pd.to_numeric(non_zero['遊客人次假日'])
non_zero['遊客人次非假日'] = pd.to_numeric(non_zero['遊客人次非假日'])

non_zero

<ipython-input-38-47e00ee18e33>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['門票收入'] = pd.to_numeric(non_zero['門票收入'])
<ipython-input-38-47e00ee18e33>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['遊客人次假日'] = pd.to_numeric(non_zero['遊客人次假日'])
<ipython-input-38-47e00ee18e33>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['遊客人次非假日'] = pd.to_numeric(non_zero['遊客人次非假日'])

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註
1,七股鹽山,"19,359","7,532",14926,11965,489850,"13,215",門票數
4,柳營尖山埤渡假村,"7,771","4,194",5897,6068,211990,"4,336",門票數
5,烏山頭水庫風景區,"22,047","1,829",6674,17202,916045,"16,278",門票數
6,曾文水庫,"16,403","1,739",10126,8016,925942,"12,684",門票數
8,虎頭埤風景區,"15,910","21,707",20777,16840,893862,"26,779",門票數
9,南元休閒農場,"2,429","1,721",2629,1521,594945,524,門票數
10,走馬瀨農場,"13,425","7,491",12442,8474,2653380,"2,869",門票數
12,頑皮世界,"21,124","2,321",12511,10934,7681858,"9,764",門票數
15,馬沙溝濱海遊憩區,796,0,676,120,93340,698,人工計數器
16,國立臺灣歷史博物館,"7,976","36,492",29403,15065,808450,"21,496",門票數
17,奇美博物館,"29,315","10,933",16635,23613,5363420,"19,123",門票數
18,臺南市美術館,"15,036","15,394",15396,15034,2070450,"20,064",門票數及人工計數
19,臺南山上花園水道博物館,"11,880","6,279",11289,6870,776480,"10,142",門票數及人工計數
20,臺南孔子廟,"7,799","3,900",5195,6504,285300,"2,779",人工計數器
22,赤崁樓,"17,670","9,986",12513,15143,1201223,"10,626",門票數
24,安平小鎮,"44,949","271,773",137318,179404,2662310,"20,592",門票數及電信人數推估(自112年1月更新統計方式)

In [40]:
# 將non_zero資料集中遊客人次假日以及非假日資料中的數值對應相加，並多增加一個欄位(遊客總人次)紀錄運算結果
non_zero['遊客總人次'] = non_zero['遊客人次假日'] + non_zero['遊客人次非假日']

# 將non_zero資料集中門票收入這一列的值除於相對應的遊客總人次，並多增加一個欄位(每張票價)紀錄運算結果
non_zero['每張票價'] = non_zero['門票收入'] / non_zero['遊客總人次']

non_zero

<ipython-input-40-32d169f6229e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['遊客總人次'] = non_zero['遊客人次假日'] + non_zero['遊客人次非假日']
<ipython-input-40-32d169f6229e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['每張票價'] = non_zero['門票收入'] / non_zero['遊客總人次']

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註,遊客總人次,每張票價
1,七股鹽山,"19,359","7,532",14926,11965,489850,"13,215",門票數,26891,18.216132
4,柳營尖山埤渡假村,"7,771","4,194",5897,6068,211990,"4,336",門票數,11965,17.717509
5,烏山頭水庫風景區,"22,047","1,829",6674,17202,916045,"16,278",門票數,23876,38.366770
6,曾文水庫,"16,403","1,739",10126,8016,925942,"12,684",門票數,18142,51.038585
8,虎頭埤風景區,"15,910","21,707",20777,16840,893862,"26,779",門票數,37617,23.762182
9,南元休閒農場,"2,429","1,721",2629,1521,594945,524,門票數,4150,143.360241
10,走馬瀨農場,"13,425","7,491",12442,8474,2653380,"2,869",門票數,20916,126.858864
12,頑皮世界,"21,124","2,321",12511,10934,7681858,"9,764",門票數,23445,327.654425
15,馬沙溝濱海遊憩區,796,0,676,120,93340,698,人工計數器,796,117.261307
16,國立臺灣歷史博物館,"7,976","36,492",29403,15065,808450,"21,496",門票數,44468,18.180489
17,奇美博物館,"29,315","10,933",16635,23613,5363420,"19,123",門票數,40248,133.259292
18,臺南市美術館,"15,036","15,394",15396,15034,2070450,"20,064",門票數及人工計數,30430,68.039763
19,臺南山上花園水道博物館,"11,880","6,279",11289,6870,776480,"10,142",門票數及人工計數,18159,42.760064
20,臺南孔子廟,"7,799","3,900",5195,6504,285300,"2,779",人工計數器,11699,24.386700
22,赤崁樓,"17,670","9,986",12513,15143,1201223,"10,626",門票數,27656,43.434445
24,安平小鎮,"44,949","271,773",137318,179404,2662310,"20,592",門票數及電信人數推估(自112年1月更新統計方式),316722,8.405826

In [9]:
non_zero['每張票價'] = non_zero['門票收入'] / non_zero['遊客人次總人次']

non_zero

<ipython-input-9-20f8b9e67aa6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_zero['每張票價'] = non_zero['門票收入'] / non_zero['遊客人次總人次']

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註,遊客人次總人次,每張票價
1,七股鹽山,"19,359","7,532",14926,11965,489850,"13,215",門票數,26891,18.216132
4,柳營尖山埤渡假村,"7,771","4,194",5897,6068,211990,"4,336",門票數,11965,17.717509
5,烏山頭水庫風景區,"22,047","1,829",6674,17202,916045,"16,278",門票數,23876,38.366770
6,曾文水庫,"16,403","1,739",10126,8016,925942,"12,684",門票數,18142,51.038585
8,虎頭埤風景區,"15,910","21,707",20777,16840,893862,"26,779",門票數,37617,23.762182
9,南元休閒農場,"2,429","1,721",2629,1521,594945,524,門票數,4150,143.360241
10,走馬瀨農場,"13,425","7,491",12442,8474,2653380,"2,869",門票數,20916,126.858864
12,頑皮世界,"21,124","2,321",12511,10934,7681858,"9,764",門票數,23445,327.654425
15,馬沙溝濱海遊憩區,796,0,676,120,93340,698,人工計數器,796,117.261307
16,國立臺灣歷史博物館,"7,976","36,492",29403,15065,808450,"21,496",門票數,44468,18.180489
17,奇美博物館,"29,315","10,933",16635,23613,5363420,"19,123",門票數,40248,133.259292
18,臺南市美術館,"15,036","15,394",15396,15034,2070450,"20,064",門票數及人工計數,30430,68.039763
19,臺南山上花園水道博物館,"11,880","6,279",11289,6870,776480,"10,142",門票數及人工計數,18159,42.760064
20,臺南孔子廟,"7,799","3,900",5195,6504,285300,"2,779",人工計數器,11699,24.386700
22,赤崁樓,"17,670","9,986",12513,15143,1201223,"10,626",門票數,27656,43.434445
24,安平小鎮,"44,949","271,773",137318,179404,2662310,"20,592",門票數及電信人數推估(自112年1月更新統計方式),316722,8.405826

In [43]:
# 將non_zero資料集中每張票價這一欄位中值最大(票價最貴)的數值儲存在max_price這個變數中

max_price = non_zero['每張票價'].max()

# 將non_zero資料集中每張票價這一欄位中值最大(票價最貴)的數值所對應的資料儲存在max_price_row這個變數中

max_price_row = non_zero[non_zero['每張票價'] == max_price]

max_price_row

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註,遊客總人次,每張票價
12,頑皮世界,"21,124","2,321",12511,10934,7681858,"9,764",門票數,23445,327.654425

In [44]:
# 將max_price_row資料集中觀光遊憩區別所對應的資料儲存在result這個變數中
result = max_price_row.loc[12,'觀光遊憩區別']

# 列印出來結果

print('票價最高的遊客景點:', result)

票價最高的遊客景點: 頑皮世界