In [1]:
# 1. 總共有多少個觀光遊憩景點會需要買門票?

import pandas as pd

# 賦予colab拜訪google drive的權限
from google.colab import drive
drive.mount('/content/drive')

# 存取我的雲端硬碟中practice這個資料夾中檔名為Tainan(2).csv.csv的檔案，並轉為Dataframe的形式
df = pd.read_csv('/content/drive/My Drive/practice/Tainan(2).csv.csv')

# # 列印出Dataframe形式的資料
df

Mounted at /content/drive

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註
0,臺灣鹽博物館,-,-,-,-,-,-,門票數(自111年閉館整修)
1,七股鹽山,"19,359","7,532","14,926","11,965","$489,850","13,215",門票數
2,北門遊客中心,NaN,"30,549","15,337","15,212",NaN,"14,892",停車數概估
3,井仔腳瓦盤鹽田,NaN,"33,111","15,531","17,580",NaN,"12,983",停車數概估
4,柳營尖山埤渡假村,"7,771","4,194","5,897","6,068","$211,990","4,336",門票數
5,烏山頭水庫風景區,"22,047","1,829","6,674","17,202","$916,045","16,278",門票數
6,曾文水庫,"16,403","1,739","10,126","8,016","$925,942","12,684",門票數
7,關子嶺溫泉區,NaN,"74,173","43,290","30,883",NaN,"165,388",自動車流監視
8,虎頭埤風景區,"15,910","21,707","20,777","16,840","$893,862","26,779",門票數
9,南元休閒農場,"2,429","1,721","2,629","1,521","$594,945",524,門票數
10,走馬瀨農場,"13,425","7,491","12,442","8,474","$2,653,380","2,869",門票數
11,烏樹林休閒園區,NaN,"7,231","5,001","2,230",NaN,"1,084",門票數
12,頑皮世界,"21,124","2,321","12,511","10,934","$7,681,858","9,764",門票數
13,南鯤鯓代天府,NaN,"756,000","453,600","302,400",NaN,"720,000",廟方估計
14,麻豆代天府,NaN,"303,750","182,250","121,500",NaN,"59,558",廟方估計
15,馬沙溝濱海遊憩區,796,NaN,676,120,"$93,340",698,人工計數器
16,國立臺灣歷史博物館,"7,976","36,492","29,403","15,065","$808,450","21,496",門票數
17,奇美博物館,"29,315","10,933","16,635","23,613","$5,363,420","19,123",門票數
18,臺南市美術館,"15,036","15,394","15,396","15,034","$2,070,450","20,064",門票數及人工計數
19,臺南山上花園水道博物館,"11,880","6,279","11,289","6,870","$776,480","10,142",門票數及人工計數
20,臺南孔子廟,"7,799","3,900","5,195","6,504","$285,300","2,779",人工計數器
21,祀典武廟,NaN,"19,359","8,759","10,600",NaN,"7,438",人工計數器
22,赤崁樓,"17,670","9,986","12,513","15,143","$1,201,223","10,626",門票數
23,大天后宮,NaN,"22,125","10,010","12,115",NaN,"8,501",人工計數器
24,安平小鎮,"44,949","271,773","137,318","179,404","$2,662,310","20,592",門票數及電信人數推估(自112年1月更新統計方式)
25,南紡購物中心,NaN,"513,878","234,870","279,008",NaN,NaN,電信數據人數推估(自112年1月起統計)
26,新化老街,NaN,"134,217","49,380","84,837",NaN,NaN,電信數據人數推估(自112年1月起統計)
27,鹽水老街,NaN,"67,722","24,239","43,483",NaN,NaN,電信數據人數推估(自112年1月起統計)
28,黃金海岸,NaN,"20,905","8,343","12,562",NaN,NaN,電信數據人數推估(自112年1月起統計)
29,藍晒圖文創園區,NaN,"342,941","163,261","179,680",NaN,NaN,電信數據人數推估(自112年1月起統計)

In [3]:
# 將第一行臺灣鹽博物館的資料刪除
df_new = df.iloc[1:, :]

# 列印出刪除後的df資料
df_new

,觀光遊憩區別,遊客人次有門票_需購票,遊客人次無門票,遊客人次假日,遊客人次非假日,門票收入,上年同月遊客人數,備註
1,七股鹽山,"19,359","7,532","14,926","11,965","$489,850","13,215",門票數
2,北門遊客中心,NaN,"30,549","15,337","15,212",NaN,"14,892",停車數概估
3,井仔腳瓦盤鹽田,NaN,"33,111","15,531","17,580",NaN,"12,983",停車數概估
4,柳營尖山埤渡假村,"7,771","4,194","5,897","6,068","$211,990","4,336",門票數
5,烏山頭水庫風景區,"22,047","1,829","6,674","17,202","$916,045","16,278",門票數
6,曾文水庫,"16,403","1,739","10,126","8,016","$925,942","12,684",門票數
7,關子嶺溫泉區,NaN,"74,173","43,290","30,883",NaN,"165,388",自動車流監視
8,虎頭埤風景區,"15,910","21,707","20,777","16,840","$893,862","26,779",門票數
9,南元休閒農場,"2,429","1,721","2,629","1,521","$594,945",524,門票數
10,走馬瀨農場,"13,425","7,491","12,442","8,474","$2,653,380","2,869",門票數
11,烏樹林休閒園區,NaN,"7,231","5,001","2,230",NaN,"1,084",門票數
12,頑皮世界,"21,124","2,321","12,511","10,934","$7,681,858","9,764",門票數
13,南鯤鯓代天府,NaN,"756,000","453,600","302,400",NaN,"720,000",廟方估計
14,麻豆代天府,NaN,"303,750","182,250","121,500",NaN,"59,558",廟方估計
15,馬沙溝濱海遊憩區,796,NaN,676,120,"$93,340",698,人工計數器
16,國立臺灣歷史博物館,"7,976","36,492","29,403","15,065","$808,450","21,496",門票數
17,奇美博物館,"29,315","10,933","16,635","23,613","$5,363,420","19,123",門票數
18,臺南市美術館,"15,036","15,394","15,396","15,034","$2,070,450","20,064",門票數及人工計數
19,臺南山上花園水道博物館,"11,880","6,279","11,289","6,870","$776,480","10,142",門票數及人工計數
20,臺南孔子廟,"7,799","3,900","5,195","6,504","$285,300","2,779",人工計數器
21,祀典武廟,NaN,"19,359","8,759","10,600",NaN,"7,438",人工計數器
22,赤崁樓,"17,670","9,986","12,513","15,143","$1,201,223","10,626",門票數
23,大天后宮,NaN,"22,125","10,010","12,115",NaN,"8,501",人工計數器
24,安平小鎮,"44,949","271,773","137,318","179,404","$2,662,310","20,592",門票數及電信人數推估(自112年1月更新統計方式)
25,南紡購物中心,NaN,"513,878","234,870","279,008",NaN,NaN,電信數據人數推估(自112年1月起統計)
26,新化老街,NaN,"134,217","49,380","84,837",NaN,NaN,電信數據人數推估(自112年1月起統計)
27,鹽水老街,NaN,"67,722","24,239","43,483",NaN,NaN,電信數據人數推估(自112年1月起統計)
28,黃金海岸,NaN,"20,905","8,343","12,562",NaN,NaN,電信數據人數推估(自112年1月起統計)
29,藍晒圖文創園區,NaN,"342,941","163,261","179,680",NaN,NaN,電信數據人數推估(自112年1月起統計)

In [8]:
# 使用counts() 計算備註這一欄中各個值出現的次數
counts = df_new['備註'].value_counts()

# 將備註中為門票數和門票數及人工計數的計算值分別儲存在count1和count2這兩個變數中
count1 = counts.get('門票數', 0)
count2 = counts.get('門票數及人工計數', 0)

# 將各自計算值相加後的結果儲存在total_count變數中
total_count = count1 + count2

# 列印出相加後的結果
print("需要買門票的遊憩景點:", total_count,"個")

需要買門票的遊憩景點: 14 個